spring:
  datasource:
    # ğŸ’¡ Trá» Ä‘áº¿n cá»•ng 5434
    url: jdbc:postgresql://localhost:5434/employee_db
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml

# ... CÃ¡c cáº¥u hÃ¬nh khÃ¡c ...